### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ksorbo** [moodleou/moodle-quizaccess_honestycheck#7] opened 2020-06-22 01:58 UTC
I am using Moodle 3.9 and get the following install error.
I have the code in the correct folder /mod/quiz/accessrule/honestycheck
honestycheck/db is there and is owned and readable by www-data

Get this error:

quizaccess_honestycheck
XML database file errors found

Informasi selanjutnya mengenai kesalahan ini

×Debug info: Errors found in XMLDB file: PATH attribute does not match file directory: mod/quiz/accessrule/honestycheck/db
Error code: ddlxmlfileerror
×Stack trace:
line 354 of /lib/ddl/database_manager.php: ddl_exception thrown
line 370 of /lib/ddl/database_manager.php: call to database_manager->load_xmldb_file()
line 654 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
line 711 of /admin/index.php: call to upgrade_noncore()

**Comment by timhunt** [comment] 2020-06-22 07:28
Are there really two 'honestycheck's in that path? If so, that is wrong. Install works for me, so I am puzzled why it is failing for you.

**Comment by ksorbo** [comment] 2020-06-23 19:37
@timhunt
There are not 2 honestycheck folders.

I removed everything and reinstalled using the git clone command

I get the same error as listed above.

Here is the content of mod/quiz/accessrule folder

root@ubuntu-s-1vcpu-1gb-sgp1-01:/var/www/html/moodle# ll mod/quiz/accessrule/
total 68
drwxr-xr-x 12 www-data www-data  4096 Jun 23 19:32 ./
drwxr-xr-x 13 www-data www-data  4096 Jun  9 16:42 ../
-rwxr-xr-x  1 www-data www-data 13276 Jun  9 16:42 accessrulebase.php*
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 delaybetweenattempts/
drwxr-xr-x  8 root     root      4096 Jun 23 19:32 honestycheck/
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 ipaddress/
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 numattempts/
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 offlineattempts/
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 openclosedate/
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 password/
drwxr-xr-x  8 www-data www-data  4096 Jun  9 16:42 seb/
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 securewindow/
drwxr-xr-x  5 www-data www-data  4096 Jun  9 16:42 timelimit/
-rwxr-xr-x  1 www-data www-data   600 Jun  9 16:42 upgrade.txt*

**Comment by timhunt** [comment] 2020-06-24 10:49
Well, the install works normally. For example, when travis-CI runs the automated tests: https://travis-ci.com/github/moodleou/moodle-quizaccess_honestycheck/jobs/353061983#L400 (That is probably completely crypic, but that verifies that a Moodle install including this plugin worked.)

So, your problem must be an issue with installing plugins into your Moodle site, not an issue with the code of this plugin.

Therefore, to get help, you probably need to ask in the 'Installation problems' forum on Moodle.org: https://moodle.org/mod/forum/view.php?id=28

**Comment by timhunt** [comment] 2020-06-28 16:43
Confirmed. https://travis-ci.com/github/moodleou/moodle-quizaccess_honestycheck/builds/173365476 it installs and works in any recent Moodle. I am going to close this issue now. I hope you manage to get it working on your server.

**Closed by timhunt** 2020-06-28 16:43 UTC
